/*----- PROTECTED REGION ID(NEO6M.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        NEO6M.cpp
//
// description : C++ source for the NEO6M class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               NEO6M are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <NEO6M.h>
#include <NEO6MClass.h>

/*----- PROTECTED REGION END -----*/	//	NEO6M.cpp

/**
 *  NEO6M class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  gps_string  |  Tango::DevString	Scalar
//  gps_array   |  Tango::DevUChar	Spectrum  ( max = 200)
//================================================================

namespace NEO6M_ns
{
/*----- PROTECTED REGION ID(NEO6M::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	NEO6M::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : NEO6M::NEO6M()
 *	Description : Constructors for a Tango device
 *                implementing the classNEO6M
 */
//--------------------------------------------------------
NEO6M::NEO6M(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(NEO6M::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::constructor_1
}
//--------------------------------------------------------
NEO6M::NEO6M(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(NEO6M::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::constructor_2
}
//--------------------------------------------------------
NEO6M::NEO6M(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(NEO6M::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : NEO6M::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void NEO6M::delete_device()
{
	DEBUG_STREAM << "NEO6M::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(NEO6M::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::delete_device
	delete[] attr_gps_string_read;
	delete[] attr_gps_array_read;
}

//--------------------------------------------------------
/**
 *	Method      : NEO6M::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void NEO6M::init_device()
{
	DEBUG_STREAM << "NEO6M::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(NEO6M::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_gps_string_read = new Tango::DevString[1];
	attr_gps_array_read = new Tango::DevUChar[200];
	/*----- PROTECTED REGION ID(NEO6M::init_device) ENABLED START -----*/
	
	//	Initialize device
	
        this->fd = com_port_open((char *) (this->com.c_str()), B9600); //Лень 9600 из baudrade переводить в B9600
        
        if (this->fd < 0) {
            set_state(Tango::DevState::FAULT);
        } else {
            set_state(Tango::DevState::OPEN);
        }
        
	/*----- PROTECTED REGION END -----*/	//	NEO6M::init_device
}

//--------------------------------------------------------
/**
 *	Method      : NEO6M::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void NEO6M::get_device_property()
{
	/*----- PROTECTED REGION ID(NEO6M::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("baudrade"));
	dev_prop.push_back(Tango::DbDatum("com"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on NEO6MClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		NEO6MClass	*ds_class =
			(static_cast<NEO6MClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize baudrade from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  baudrade;
		else {
			//	Try to initialize baudrade from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  baudrade;
		}
		//	And try to extract baudrade value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  baudrade;

		//	Try to initialize com from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  com;
		else {
			//	Try to initialize com from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  com;
		}
		//	And try to extract com value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  com;

	}

	/*----- PROTECTED REGION ID(NEO6M::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : NEO6M::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void NEO6M::always_executed_hook()
{
	DEBUG_STREAM << "NEO6M::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(NEO6M::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : NEO6M::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void NEO6M::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "NEO6M::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(NEO6M::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
        this->gps = com_port_read(this->fd, &this->size, 2);
        
	/*----- PROTECTED REGION END -----*/	//	NEO6M::read_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute gps_string related method
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void NEO6M::read_gps_string(Tango::Attribute &attr)
{
	DEBUG_STREAM << "NEO6M::read_gps_string(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(NEO6M::read_gps_string) ENABLED START -----*/
	//	Set the attribute value
                
        *this->attr_gps_string_read = Tango::string_dup(this->gps.c_str());
        
	attr.set_value(attr_gps_string_read);
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::read_gps_string
}
//--------------------------------------------------------
/**
 *	Read attribute gps_array related method
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Spectrum max = 200
 */
//--------------------------------------------------------
void NEO6M::read_gps_array(Tango::Attribute &attr)
{
	DEBUG_STREAM << "NEO6M::read_gps_array(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(NEO6M::read_gps_array) ENABLED START -----*/
	//	Set the attribute value
        
        memcpy(attr_gps_array_read, this->gps.c_str(), this->gps.size());
                        
	attr.set_value(attr_gps_array_read, gps.size());
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::read_gps_array
}

//--------------------------------------------------------
/**
 *	Method      : NEO6M::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void NEO6M::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(NEO6M::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : NEO6M::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void NEO6M::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(NEO6M::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::add_dynamic_commands
}

/*----- PROTECTED REGION ID(NEO6M::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	NEO6M::namespace_ending
} //	namespace
