/*----- PROTECTED REGION ID(NEO6MStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        NEO6MStateMachine.cpp
//
// description : State machine file for the NEO6M class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <NEO6M.h>

/*----- PROTECTED REGION END -----*/	//	NEO6M::NEO6MStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  OFF     |  
//  FAULT   |  


namespace NEO6M_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : NEO6M::is_gps_string_allowed()
 *	Description : Execution allowed for gps_string attribute
 */
//--------------------------------------------------------
bool NEO6M::is_gps_string_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for gps_string attribute in read access.
	/*----- PROTECTED REGION ID(NEO6M::gps_stringStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::gps_stringStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : NEO6M::is_gps_array_allowed()
 *	Description : Execution allowed for gps_array attribute
 */
//--------------------------------------------------------
bool NEO6M::is_gps_array_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for gps_array attribute in read access.
	/*----- PROTECTED REGION ID(NEO6M::gps_arrayStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	NEO6M::gps_arrayStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(NEO6M::NEO6MStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	NEO6M::NEO6MStateAllowed.AdditionalMethods

}	//	End of namespace
