/*----- PROTECTED REGION ID(NEO6M.h) ENABLED START -----*/
//=============================================================================
//
// file :        NEO6M.h
//
// description : Include file for the NEO6M class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef NEO6M_H
#define NEO6M_H

#include <tango.h>

#include "com.h"

/*----- PROTECTED REGION END -----*/	//	NEO6M.h

/**
 *  NEO6M class description:
 *    
 */

namespace NEO6M_ns
{
/*----- PROTECTED REGION ID(NEO6M::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	NEO6M::Additional Class Declarations

class NEO6M : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(NEO6M::Data Members) ENABLED START -----*/

//	Add your own data members
        int fd;
        int size;
        
        string gps;
        
/*----- PROTECTED REGION END -----*/	//	NEO6M::Data Members

//	Device property data members
public:
	//	baudrade:	
	Tango::DevLong	baudrade;
	//	com:	
	string	com;

//	Attribute data members
public:
	Tango::DevString	*attr_gps_string_read;
	Tango::DevUChar	*attr_gps_array_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	NEO6M(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	NEO6M(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	NEO6M(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~NEO6M() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : NEO6M::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute gps_string related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_gps_string(Tango::Attribute &attr);
	virtual bool is_gps_string_allowed(Tango::AttReqType type);
/**
 *	Attribute gps_array related methods
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Spectrum max = 200
 */
	virtual void read_gps_array(Tango::Attribute &attr);
	virtual bool is_gps_array_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : NEO6M::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command GPSArray related method
	 *	Description: 
	 *
	 *	@returns 
	 */
	virtual Tango::DevVarCharArray *gpsarray();
	virtual bool is_GPSArray_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : NEO6M::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(NEO6M::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	NEO6M::Additional Method prototypes
};

/*----- PROTECTED REGION ID(NEO6M::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	NEO6M::Additional Classes Definitions

}	//	End of namespace

#endif   //	NEO6M_H
