/*----- PROTECTED REGION ID(NEO6MClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        NEO6MClass.h
//
// description : Include for the NEO6M root class.
//               This class is the singleton class for
//                the NEO6M device class.
//               It contains all properties and methods which the 
//               NEO6M requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef NEO6MClass_H
#define NEO6MClass_H

#include <tango.h>
#include <NEO6M.h>


/*----- PROTECTED REGION END -----*/	//	NEO6MClass.h


namespace NEO6M_ns
{
/*----- PROTECTED REGION ID(NEO6MClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	NEO6MClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute gps_string class definition
class gps_stringAttrib: public Tango::Attr
{
public:
	gps_stringAttrib():Attr("gps_string",
			Tango::DEV_STRING, Tango::READ) {};
	~gps_stringAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<NEO6M *>(dev))->read_gps_string(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<NEO6M *>(dev))->is_gps_string_allowed(ty);}
};

//	Attribute gps_array class definition
class gps_arrayAttrib: public Tango::SpectrumAttr
{
public:
	gps_arrayAttrib():SpectrumAttr("gps_array",
			Tango::DEV_UCHAR, Tango::READ, 200) {};
	~gps_arrayAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<NEO6M *>(dev))->read_gps_array(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<NEO6M *>(dev))->is_gps_array_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command GPSArray class definition
class GPSArrayClass : public Tango::Command
{
public:
	GPSArrayClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	GPSArrayClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~GPSArrayClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<NEO6M *>(dev))->is_GPSArray_allowed(any);}
};


/**
 *	The NEO6MClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  NEO6MClass : public Tango::DeviceClass
#else
class NEO6MClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(NEO6MClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	NEO6MClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static NEO6MClass *init(const char *);
		static NEO6MClass *instance();
		~NEO6MClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		NEO6MClass(string &);
		static NEO6MClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	NEO6M_H
